DEBUG: Executing python function do_clean
ERROR: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_clean(d)
     0003:
File: '/home/abdelaziz/mylayer/printhello.bb', lineno: 20, function: do_clean
     0016:    import os
     0017:
     0018:    folder_path = "/home/abdelaziz/hello/tmp"
     0019:
 *** 0020:    if os.path.exists(tmp):
     0021:        shutil.rmtree(tmp)
     0022:}
     0023:
     0024:
Exception: NameError: name 'tmp' is not defined

DEBUG: Python function do_clean finished
